# Generated by Django 3.2.5 on 2024-06-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('email', 'phone')},
        ),
    ]
